name = "stella-catering-backend"
main = "backend/src/index.ts"
compatibility_date = "2025-02-24"
compatibility_flags = ["nodejs_compat"]
account_id = "04a311dd63265e896ca15a8e8124f144"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "production-jwt-secret-stella-catering-2026-edge"
CORS_ORIGIN = "*"
PUBLIC_R2_URL = "https://media.stellascatering.com"

[[d1_databases]]
binding = "DB"
database_name = "stella-db"
database_id = "085facb9-112d-4c26-b325-ac7bad8e3552"
migrations_dir = "backend/drizzle"
